// app/pages/cv/PhotoOverlay.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { usePhoto } from '@/composables/usePhoto'

const { photo } = usePhoto()
const isSelected = ref(false)
const wrapperRef = ref<HTMLElement | null>(null)

// Dragging state
let isDragging = false
let startX = 0
let startY = 0
let startLeft = 0
let startTop = 0

// Resizing state
let isResizing = false
let resizeHandle = ''
let startWidth = 0
let startHeight = 0 // Not used for width-based aspect ratio, but good to have
let aspectRatio = 1
let startBottomPct = 0
let imageAspectRatio = 1
let parentWidth = 0
let parentHeight = 0

function onMouseDown(e: MouseEvent) {
  if (!isSelected.value) {
    isSelected.value = true
    return
  }
  e.preventDefault()
  e.stopPropagation()
  
  isDragging = true
  startX = e.clientX
  startY = e.clientY
  startLeft = photo.value.x
  startTop = photo.value.y
  
  window.addEventListener('mousemove', onMouseMove)
  window.addEventListener('mouseup', onMouseUp)
}

function onResizeStart(e: MouseEvent, handle: string) {
  e.preventDefault()
  e.stopPropagation()
  
  isResizing = true
  resizeHandle = handle
  startX = e.clientX
  startY = e.clientY
  startWidth = photo.value.width
  startLeft = photo.value.x
  startTop = photo.value.y
  
  if (wrapperRef.value && wrapperRef.value.parentElement) {
    const rect = wrapperRef.value.getBoundingClientRect()
    const parentRect = wrapperRef.value.parentElement.getBoundingClientRect()
    parentWidth = parentRect.width
    parentHeight = parentRect.height
    imageAspectRatio = rect.width / rect.height
    startBottomPct = startTop + (rect.height / parentHeight) * 100
  }
  
  window.addEventListener('mousemove', onResizeMove)
  window.addEventListener('mouseup', onResizeUp)
}

function onMouseMove(e: MouseEvent) {
  if (!isDragging || !wrapperRef.value) return
  
  const parent = wrapperRef.value.parentElement
  if (!parent) return
  const parentRect = parent.getBoundingClientRect()
  
  const dx = e.clientX - startX
  const dy = e.clientY - startY
  
  const dxPct = (dx / parentRect.width) * 100
  const dyPct = (dy / parentRect.height) * 100
  
  photo.value.x = Math.max(0, Math.min(100 - photo.value.width, startLeft + dxPct))
  photo.value.y = Math.max(0, Math.min(100, startTop + dyPct))
}

function onMouseUp() {
  isDragging = false
  window.removeEventListener('mousemove', onMouseMove)
  window.removeEventListener('mouseup', onMouseUp)
}

function onResizeMove(e: MouseEvent) {
  if (!isResizing || !wrapperRef.value) return
  
  const parent = wrapperRef.value.parentElement
  if (!parent) return
  const parentRect = parent.getBoundingClientRect()
  
  const dx = e.clientX - startX
  const dy = e.clientY - startY
  
  const dxPct = (dx / parentRect.width) * 100
  const dyPct = (dy / parentRect.height) * 100
  
  if (resizeHandle.includes('right')) {
    photo.value.width = Math.max(5, Math.min(100 - startLeft, startWidth + dxPct))
  } else if (resizeHandle.includes('left')) {
    const newWidth = Math.max(5, Math.min(startLeft + startWidth, startWidth - dxPct))
    const newLeft = startLeft + (startWidth - newWidth)
    if (newLeft >= 0) {
        photo.value.width = newWidth
        photo.value.x = newLeft
    }
  }
  
  if (resizeHandle === 'top-left') {
    // Calculate new height based on new width and aspect ratio
    const currentWidthPct = photo.value.width
    const currentWidthPx = (currentWidthPct / 100) * parentWidth
    const newHeightPx = currentWidthPx / imageAspectRatio
    const newHeightPct = (newHeightPx / parentHeight) * 100
    
    // Update Y so that Bottom stays at startBottomPct
    photo.value.y = startBottomPct - newHeightPct
  }
}

function onResizeUp() {
  isResizing = false
  window.removeEventListener('mousemove', onResizeMove)
  window.removeEventListener('mouseup', onResizeUp)
}

function remove() {
  photo.value.src = ''
}

// Click outside to deselect
function onWindowClick(e: MouseEvent) {
  if (isSelected.value && wrapperRef.value && !wrapperRef.value.contains(e.target as Node)) {
    isSelected.value = false
  }
}

onMounted(() => {
  window.addEventListener('mousedown', onWindowClick)
})

onUnmounted(() => {
  window.removeEventListener('mousedown', onWindowClick)
  window.removeEventListener('mousemove', onMouseMove)
  window.removeEventListener('mouseup', onMouseUp)
  window.removeEventListener('mousemove', onResizeMove)
  window.removeEventListener('mouseup', onResizeUp)
})
</script>

<template>
  <div
    v-if="photo.src"
    ref="wrapperRef"
    class="absolute select-none"
    :style="{
      left: `${photo.x}%`,
      top: `${photo.y}%`,
      width: `${photo.width}%`,
      zIndex: 50
    }"
    @mousedown="onMouseDown"
  >
    <img
      :src="photo.src"
      class="w-full h-auto block shadow-sm cursor-move"
      :class="{ 'ring-2 ring-blue-500': isSelected }"
      draggable="false"
    />
    
    <template v-if="isSelected">
      <!-- Delete Button -->
      <button
        class="absolute -top-2 -right-2 w-5 h-5 bg-red-500 text-white rounded-full flex items-center justify-center text-xs hover:bg-red-600 z-50 shadow-sm"
        @click.stop="remove"
      >
        ✕
      </button>
      
      <!-- Anchors -->
      <div
        class="absolute -top-1 -left-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nwse-resize z-50"
        @mousedown.stop="onResizeStart($event, 'top-left')"
      ></div>
      <div
        class="absolute -bottom-1 -left-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nesw-resize z-50"
        @mousedown.stop="onResizeStart($event, 'bottom-left')"
      ></div>
      <div
        class="absolute -bottom-1 -right-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nwse-resize z-50"
        @mousedown.stop="onResizeStart($event, 'bottom-right')"
      ></div>
    </template>
  </div>
</template>

// apps/web/components/cv/photo-overlay.tsx
'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { usePhoto } from '@/hooks/use-photo';
import { X } from 'lucide-react';

export function PhotoOverlay() {
  const { photo, setPhoto } = usePhoto();
  const [isSelected, setIsSelected] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);

  // 拖拽状态
  const dragState = useRef({
    isDragging: false,
    startX: 0,
    startY: 0,
    startLeft: 0,
    startTop: 0,
  });

  // 调整大小状态
  const resizeState = useRef({
    isResizing: false,
    handle: '',
    startX: 0,
    startY: 0,
    startWidth: 0,
    startLeft: 0,
    startTop: 0,
    startBottomPct: 0,
    imageAspectRatio: 1,
    parentWidth: 0,
    parentHeight: 0,
  });

  const onMouseDown = useCallback((e: React.MouseEvent) => {
    if (!isSelected) {
      setIsSelected(true);
      return;
    }

    e.preventDefault();
    e.stopPropagation();

    dragState.current.isDragging = true;
    dragState.current.startX = e.clientX;
    dragState.current.startY = e.clientY;
    dragState.current.startLeft = photo.x;
    dragState.current.startTop = photo.y;
  }, [isSelected, photo.x, photo.y]);

  const onResizeStart = useCallback((e: React.MouseEvent, handle: string) => {
    e.preventDefault();
    e.stopPropagation();

    resizeState.current.isResizing = true;
    resizeState.current.handle = handle;
    resizeState.current.startX = e.clientX;
    resizeState.current.startY = e.clientY;
    resizeState.current.startWidth = photo.width;
    resizeState.current.startLeft = photo.x;
    resizeState.current.startTop = photo.y;

    if (wrapperRef.current && wrapperRef.current.parentElement) {
      const rect = wrapperRef.current.getBoundingClientRect();
      const parentRect = wrapperRef.current.parentElement.getBoundingClientRect();
      resizeState.current.parentWidth = parentRect.width;
      resizeState.current.parentHeight = parentRect.height;
      resizeState.current.imageAspectRatio = rect.width / rect.height;
      resizeState.current.startBottomPct = photo.y + (rect.height / parentRect.height) * 100;
    }
  }, [photo.width, photo.x, photo.y]);

  useEffect(() => {
    const onMouseMove = (e: MouseEvent) => {
      // 处理拖拽
      if (dragState.current.isDragging && wrapperRef.current) {
        const parent = wrapperRef.current.parentElement;
        if (!parent) return;
        const parentRect = parent.getBoundingClientRect();

        const dx = e.clientX - dragState.current.startX;
        const dy = e.clientY - dragState.current.startY;

        const dxPct = (dx / parentRect.width) * 100;
        const dyPct = (dy / parentRect.height) * 100;

        const newX = Math.max(0, Math.min(100 - photo.width, dragState.current.startLeft + dxPct));
        const newY = Math.max(0, Math.min(100, dragState.current.startTop + dyPct));

        setPhoto({ ...photo, x: newX, y: newY });
      }

      // 处理调整大小
      if (resizeState.current.isResizing && wrapperRef.current) {
        const parent = wrapperRef.current.parentElement;
        if (!parent) return;
        const parentRect = parent.getBoundingClientRect();

        const dx = e.clientX - resizeState.current.startX;
        const dy = e.clientY - resizeState.current.startY;

        const dxPct = (dx / parentRect.width) * 100;
        const dyPct = (dy / parentRect.height) * 100;

        let newWidth = resizeState.current.startWidth;
        let newLeft = resizeState.current.startLeft;
        let newTop = resizeState.current.startTop;

        if (resizeState.current.handle.includes('right')) {
          newWidth = Math.max(5, Math.min(100 - resizeState.current.startLeft, resizeState.current.startWidth + dxPct));
        } else if (resizeState.current.handle.includes('left')) {
          const tempWidth = Math.max(5, Math.min(resizeState.current.startLeft + resizeState.current.startWidth, resizeState.current.startWidth - dxPct));
          const tempLeft = resizeState.current.startLeft + (resizeState.current.startWidth - tempWidth);
          if (tempLeft >= 0) {
            newWidth = tempWidth;
            newLeft = tempLeft;
          }
        }

        if (resizeState.current.handle === 'top-left') {
          const currentWidthPx = (newWidth / 100) * resizeState.current.parentWidth;
          const newHeightPx = currentWidthPx / resizeState.current.imageAspectRatio;
          const newHeightPct = (newHeightPx / resizeState.current.parentHeight) * 100;
          newTop = resizeState.current.startBottomPct - newHeightPct;
        }

        setPhoto({ ...photo, x: newLeft, y: newTop, width: newWidth });
      }
    };

    const onMouseUp = () => {
      dragState.current.isDragging = false;
      resizeState.current.isResizing = false;
    };

    const onWindowClick = (e: MouseEvent) => {
      if (isSelected && wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        setIsSelected(false);
      }
    };

    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mouseup', onMouseUp);
    window.addEventListener('mousedown', onWindowClick);

    return () => {
      window.removeEventListener('mousemove', onMouseMove);
      window.removeEventListener('mouseup', onMouseUp);
      window.removeEventListener('mousedown', onWindowClick);
    };
  }, [isSelected, photo, setPhoto]);

  const remove = useCallback(() => {
    setPhoto({ ...photo, src: '' });
  }, [photo, setPhoto]);

  if (!photo.src) return null;

  return (
    <div
      ref={wrapperRef}
      className="absolute select-none"
      style={{
        left: `${photo.x}%`,
        top: `${photo.y}%`,
        width: `${photo.width}%`,
        zIndex: 50,
      }}
      onMouseDown={onMouseDown}
    >
      <img
        src={photo.src}
        alt="Photo"
        className={`w-full h-auto block shadow-sm ${isSelected ? 'ring-2 ring-blue-500' : ''}`}
        style={{ cursor: isSelected ? 'move' : 'pointer' }}
        draggable={false}
      />

      {isSelected && (
        <>
          {/* 删除按钮 */}
          <button
            className="absolute -top-2 -right-2 w-5 h-5 bg-red-500 text-white rounded-full flex items-center justify-center text-xs hover:bg-red-600 z-50 shadow-sm"
            onClick={(e) => {
              e.stopPropagation();
              remove();
            }}
          >
            <X className="w-3 h-3" />
          </button>

          {/* 调整大小锚点 */}
          <div
            className="absolute -top-1 -left-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nwse-resize z-50"
            onMouseDown={(e) => onResizeStart(e, 'top-left')}
          />
          <div
            className="absolute -bottom-1 -left-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nesw-resize z-50"
            onMouseDown={(e) => onResizeStart(e, 'bottom-left')}
          />
          <div
            className="absolute -bottom-1 -right-1 w-3 h-3 bg-primary border border-white rounded-full cursor-nwse-resize z-50"
            onMouseDown={(e) => onResizeStart(e, 'bottom-right')}
          />
        </>
      )}
    </div>
  );
}
